# docker-compose.yml
version: '3.8'

services:
  schedule-optimizer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schedule-optimizer
    restart: unless-stopped
    ports:
      - "48920:48920"
    volumes:
      # Mounted persistent data
      - schedule_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:48920/schedule-optimizer"]
      interval: 30s
      timeout: 10s
      retries: 3

# Persistent course and server stats
volumes:
  schedule_data:
    name: schedule_optimizer_data
