# docker-compose.yml
version: '3.8'

services:
  schedule-optimizer:
    build: .
    container_name: schedule-optimizer
    restart: unless-stopped
    ports:
      - "48920:48920"
    # Persistent course and server stats
    volumes:
      - /app/data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:48920/schedule-optimizer"]
      interval: 30s
      timeout: 10s
      retries: 3

# Persistent course and server stats
volumes:
  schedule_data:
