// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type GenerationLog struct {
	ID                 int64          `json:"id"`
	Term               sql.NullString `json:"term"`
	CoursesRequested   sql.NullString `json:"courses_requested"`
	SchedulesGenerated sql.NullInt64  `json:"schedules_generated"`
	SessionID          sql.NullString `json:"session_id"`
	CreatedAt          sql.NullTime   `json:"created_at"`
}

type Instructor struct {
	ID        int64          `json:"id"`
	SectionID int64          `json:"section_id"`
	BannerID  sql.NullString `json:"banner_id"`
	Name      string         `json:"name"`
	Email     sql.NullString `json:"email"`
	IsPrimary sql.NullInt64  `json:"is_primary"`
}

type MeetingTime struct {
	ID                  int64           `json:"id"`
	SectionID           int64           `json:"section_id"`
	StartTime           sql.NullString  `json:"start_time"`
	EndTime             sql.NullString  `json:"end_time"`
	StartDate           sql.NullString  `json:"start_date"`
	EndDate             sql.NullString  `json:"end_date"`
	Building            sql.NullString  `json:"building"`
	BuildingDescription sql.NullString  `json:"building_description"`
	Room                sql.NullString  `json:"room"`
	Monday              sql.NullInt64   `json:"monday"`
	Tuesday             sql.NullInt64   `json:"tuesday"`
	Wednesday           sql.NullInt64   `json:"wednesday"`
	Thursday            sql.NullInt64   `json:"thursday"`
	Friday              sql.NullInt64   `json:"friday"`
	Saturday            sql.NullInt64   `json:"saturday"`
	Sunday              sql.NullInt64   `json:"sunday"`
	ScheduleType        sql.NullString  `json:"schedule_type"`
	MeetingType         sql.NullString  `json:"meeting_type"`
	CreditHours         sql.NullFloat64 `json:"credit_hours"`
	HoursPerWeek        sql.NullFloat64 `json:"hours_per_week"`
}

type SearchLog struct {
	ID           int64          `json:"id"`
	Query        string         `json:"query"`
	Term         sql.NullString `json:"term"`
	ResultsCount sql.NullInt64  `json:"results_count"`
	SessionID    sql.NullString `json:"session_id"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type Section struct {
	ID                      int64          `json:"id"`
	Term                    string         `json:"term"`
	Crn                     string         `json:"crn"`
	Subject                 string         `json:"subject"`
	SubjectDescription      sql.NullString `json:"subject_description"`
	CourseNumber            string         `json:"course_number"`
	SequenceNumber          sql.NullString `json:"sequence_number"`
	Title                   string         `json:"title"`
	Campus                  sql.NullString `json:"campus"`
	ScheduleType            sql.NullString `json:"schedule_type"`
	InstructionalMethod     sql.NullString `json:"instructional_method"`
	InstructionalMethodDesc sql.NullString `json:"instructional_method_desc"`
	CreditHoursLow          sql.NullInt64  `json:"credit_hours_low"`
	CreditHoursHigh         sql.NullInt64  `json:"credit_hours_high"`
	Enrollment              sql.NullInt64  `json:"enrollment"`
	MaxEnrollment           sql.NullInt64  `json:"max_enrollment"`
	SeatsAvailable          sql.NullInt64  `json:"seats_available"`
	WaitCapacity            sql.NullInt64  `json:"wait_capacity"`
	WaitCount               sql.NullInt64  `json:"wait_count"`
	IsOpen                  sql.NullInt64  `json:"is_open"`
	UpdatedAt               sql.NullTime   `json:"updated_at"`
}

type SectionAttribute struct {
	ID          int64          `json:"id"`
	SectionID   int64          `json:"section_id"`
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
}

type Term struct {
	Code          string       `json:"code"`
	Description   string       `json:"description"`
	LastScrapedAt sql.NullTime `json:"last_scraped_at"`
}
